#' json_intake: Generates a json file for intake data
#'
#' This function generates a json file for intake data
#'
#' @return A string with data stored in JSON format containing meta-data
#'
#'
#' @export

json_intake <- function() {

  intake_list <- list(
    participant_id = list( Description = 'participant id number'),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1',
                                          '2' =	'Child visit protocol 2',
                                          '3' =	'Child visit protocol 3',
                                          '4'	= 'Child visit protocol 4',
                                          '5'	= 'Child visit protocol 5')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    preload_condition = list( Description = 'Preload condition',
                              Levels = list ('0' = 'no preload',
                                             '1' = 'apple slices',
                                             '2' = 'apple sauce',
                                             '3' = 'apple juice',
                                             '4' = 'apple juice sweetend with non-nutritive sweetener (i.e., diet)')),
    preload_condition = list( Description = 'Preload condition',
                              Levels = list ('0' = 'no preload',
                                             '1' = 'apple slices',
                                             '2' = 'apple sauce',
                                             '3' = 'apple juice',
                                             '4' = 'apple juice sweetend with non-nutritive sweetener (i.e., diet)')),
    preload_pre_w_o_plate = list( Description = 'Pre-preload weight without plate/bowl',
                              Unit = "grams"),
    preload_w_plate = list( Description = 're-preload weight with weight of plate/bowl',
                                 Unit = "grams"),
    preload_servecup_weight = list( Description = 'total weight of the 16 empty souffle cups used to serve the preload',
                            Unit = "grams"),
    preload_post_w_cup_plate = list( Description = 'Post-preload weight of the 16 souffle cups with any remaining preload and the pre-bowl/plate all together',
                            Unit = "grams"),
    #mac and cheese
    mac_pre_w_o_plate_serv1 = list( Description = 'Pre-meal weight of macaroni and cheese without plate for serving 1',
                                Unit = "grams"),
    mac_pre_w_plate_serv1 = list( Description = 'Pre-meal weight of macaroni and cheese with plate for serving 1',
                              Unit = "grams"),
    mac_pre_w_o_plate_serv2 = list( Description = 'Pre-meal weight of macaroni and cheese without plate for serving 2',
                                    Unit = "grams"),
    mac_pre_w_plate_serv2 = list( Description = 'Pre-meal weight of macaroni and cheese with plate for serving 2',
                                  Unit = "grams"),
    mac_pre_w_o_plate_serv3 = list( Description = 'Pre-meal weight of macaroni and cheese without plate for serving 3',
                                    Unit = "grams"),
    mac_pre_w_plate_serv3 = list( Description = 'Pre-meal weight of macaroni and cheese with plate for serving 3',
                                  Unit = "grams"),
    mac_pre_w_o_plate_serv4 = list( Description = 'Pre-meal weight of macaroni and cheese without plate for serving 4',
                                    Unit = "grams"),
    mac_pre_w_plate_serv4 = list( Description = 'Pre-meal weight of macaroni and cheese with plate for serving 4',
                                  Unit = "grams"),
    mac_post_w_plate_serv1 = list( Description = 'Post-meal weight of macaroni and cheese with plate for serving 1',
                                Unit = "grams"),
    mac_post_w_plate_serv2 = list( Description = 'Post-meal weight of macaroni and cheese with plate for serving 2',
                                   Unit = "grams"),
    mac_post_w_plate_serv3 = list( Description = 'Post-meal weight of macaroni and cheese with plate for serving 3',
                                   Unit = "grams"),
    mac_post_w_plate_serv4 = list( Description = 'Post-meal weight of macaroni and cheese with plate for serving 4',
                                   Unit = "grams"),
    mac_serving2 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    mac_serving3 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    mac_serving4 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    mac_pre_w_o_plate = list( Description = 'Total pre-meal weight of macaroni and cheese without plate for all servings',
                                    Unit = "grams"),
    mac_pre_w_plate = list( Description = 'Total pre-meal weight of macaroni and cheese with plate for all servings',
                                  Unit = "grams"),
    mac_post_w_plate = list( Description = 'Total post-meal weight of macaroni and cheese with plate ffor all servings',
                                   Unit = "grams"),

    #broccoli
    broccoli_pre_w_o_plate_serv1 = list( Description = 'Pre-meal weight of broccoli without plate for serving 1',
                                    Unit = "grams"),
    broccoli_pre_w_plate_serv1 = list( Description = 'Pre-meal weight of broccoli with plate for serving 1',
                                  Unit = "grams"),
    broccoli_pre_w_o_plate_serv2 = list( Description = 'Pre-meal weight of broccoli without plate for serving 2',
                                    Unit = "grams"),
    broccoli_pre_w_plate_serv2 = list( Description = 'Pre-meal weight of broccoli with plate for serving 2',
                                  Unit = "grams"),
    broccoli_pre_w_o_plate_serv3 = list( Description = 'Pre-meal weight of broccoli without plate for serving 3',
                                    Unit = "grams"),
    broccoli_pre_w_plate_serv3 = list( Description = 'Pre-meal weight of broccoli with plate for serving 3',
                                  Unit = "grams"),
    broccoli_pre_w_o_plate_serv4 = list( Description = 'Pre-meal weight of broccoli without plate for serving 4',
                                    Unit = "grams"),
    broccoli_pre_w_plate_serv4 = list( Description = 'Pre-meal weight of broccoli with plate for serving 4',
                                  Unit = "grams"),
    broccoli_post_w_plate_serv1 = list( Description = 'Post-meal weight of broccoli with plate for serving 1',
                                   Unit = "grams"),
    broccoli_post_w_plate_serv2 = list( Description = 'Post-meal weight of broccoli with plate for serving 2',
                                   Unit = "grams"),
    broccoli_post_w_plate_serv3 = list( Description = 'Post-meal weight of broccoli with plate for serving 3',
                                   Unit = "grams"),
    broccoli_post_w_plate_serv4 = list( Description = 'Post-meal weight of broccoli with plate for serving 4',
                                   Unit = "grams"),
    broccoli_serving2 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    broccoli_serving3 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    broccoli_serving4 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    broccoli_pre_w_o_plate = list( Description = 'Total pre-meal weight of broccoli without plate for all servings',
                              Unit = "grams"),
    broccoli_pre_w_plate = list( Description = 'Total pre-meal weight of broccoli with plate for all servings',
                            Unit = "grams"),
    broccoli_post_w_plate = list( Description = 'Total post-meal weight of broccoli with plate ffor all servings',
                             Unit = "grams"),

    #grapes
    grapes_pre_w_o_plate_serv1 = list( Description = 'Pre-meal weight of grapes without plate for serving 1',
                                    Unit = "grams"),
    grapes_pre_w_plate_serv1 = list( Description = 'Pre-meal weight of grapes with plate for serving 1',
                                  Unit = "grams"),
    grapes_pre_w_o_plate_serv2 = list( Description = 'Pre-meal weight of grapes without plate for serving 2',
                                    Unit = "grams"),
    grapes_pre_w_plate_serv2 = list( Description = 'Pre-meal weight of grapes with plate for serving 2',
                                  Unit = "grams"),
    grapes_pre_w_o_plate_serv3 = list( Description = 'Pre-meal weight of grapes without plate for serving 3',
                                    Unit = "grams"),
    grapes_pre_w_plate_serv3 = list( Description = 'Pre-meal weight of grapes with plate for serving 3',
                                  Unit = "grams"),
    grapes_pre_w_o_plate_serv4 = list( Description = 'Pre-meal weight of grapes without plate for serving 4',
                                    Unit = "grams"),
    grapes_pre_w_plate_serv4 = list( Description = 'Pre-meal weight of grapes with plate for serving 4',
                                  Unit = "grams"),
    grapes_post_w_plate_serv1 = list( Description = 'Post-meal weight of grapes with plate for serving 1',
                                   Unit = "grams"),
    grapes_post_w_plate_serv2 = list( Description = 'Post-meal weight of grapes with plate for serving 2',
                                   Unit = "grams"),
    grapes_post_w_plate_serv3 = list( Description = 'Post-meal weight of grapes with plate for serving 3',
                                   Unit = "grams"),
    grapes_post_w_plate_serv4 = list( Description = 'Post-meal weight of grapes with plate for serving 4',
                                   Unit = "grams"),
    grapes_serving2 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    grapes_serving3 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    grapes_serving4 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    grapes_pre_w_o_plate = list( Description = 'Total pre-meal weight of grapes without plate for all servings',
                              Unit = "grams"),
    grapes_pre_w_plate = list( Description = 'Total pre-meal weight of grapes with plate for all servings',
                            Unit = "grams"),
    grapes_post_w_plate = list( Description = 'Total post-meal weight of grapes with plate ffor all servings',
                             Unit = "grams"),

    #carrots
    carrots_pre_w_o_plate_serv1 = list( Description = 'Pre-meal weight of carrots without plate for serving 1',
                                    Unit = "grams"),
    carrots_pre_w_plate_serv1 = list( Description = 'Pre-meal weight of carrots with plate for serving 1',
                                  Unit = "grams"),
    carrots_pre_w_o_plate_serv2 = list( Description = 'Pre-meal weight of carrots without plate for serving 2',
                                    Unit = "grams"),
    carrots_pre_w_plate_serv2 = list( Description = 'Pre-meal weight of carrots with plate for serving 2',
                                  Unit = "grams"),
    carrots_pre_w_o_plate_serv3 = list( Description = 'Pre-meal weight of carrots without plate for serving 3',
                                    Unit = "grams"),
    carrots_pre_w_plate_serv3 = list( Description = 'Pre-meal weight of carrots with plate for serving 3',
                                  Unit = "grams"),
    carrots_pre_w_o_plate_serv4 = list( Description = 'Pre-meal weight of carrots without plate for serving 4',
                                    Unit = "grams"),
    carrots_pre_w_plate_serv4 = list( Description = 'Pre-meal weight of carrots with plate for serving 4',
                                  Unit = "grams"),
    carrots_post_w_plate_serv1 = list( Description = 'Post-meal weight of carrots with plate for serving 1',
                                   Unit = "grams"),
    carrots_post_w_plate_serv2 = list( Description = 'Post-meal weight of carrots with plate for serving 2',
                                   Unit = "grams"),
    carrots_post_w_plate_serv3 = list( Description = 'Post-meal weight of carrots with plate for serving 3',
                                   Unit = "grams"),
    carrots_post_w_plate_serv4 = list( Description = 'Post-meal weight of carrots with plate for serving 4',
                                   Unit = "grams"),
    carrots_serving2 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    carrots_serving3 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    carrots_serving4 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    carrots_pre_w_o_plate = list( Description = 'Total pre-meal weight of carrots without plate for all servings',
                              Unit = "grams"),
    carrots_pre_w_plate = list( Description = 'Total pre-meal weight of carrots with plate for all servings',
                            Unit = "grams"),
    carrots_post_w_plate = list( Description = 'Total post-meal weight of carrots with plate ffor all servings',
                             Unit = "grams"),

    #graham cracker
    graham_pre_w_o_plate_serv1 = list( Description = 'Pre-meal weight of graham cracker without plate for serving 1',
                                    Unit = "grams"),
    graham_pre_w_plate_serv1 = list( Description = 'Pre-meal weight of graham cracker with plate for serving 1',
                                  Unit = "grams"),
    graham_pre_w_o_plate_serv2 = list( Description = 'Pre-meal weight of graham cracker without plate for serving 2',
                                    Unit = "grams"),
    graham_pre_w_plate_serv2 = list( Description = 'Pre-meal weight of graham cracker with plate for serving 2',
                                  Unit = "grams"),
    graham_pre_w_o_plate_serv3 = list( Description = 'Pre-meal weight of graham cracker without plate for serving 3',
                                    Unit = "grams"),
    graham_pre_w_plate_serv3 = list( Description = 'Pre-meal weight of graham cracker with plate for serving 3',
                                  Unit = "grams"),
    graham_pre_w_o_plate_serv4 = list( Description = 'Pre-meal weight of graham cracker without plate for serving 4',
                                    Unit = "grams"),
    graham_pre_w_plate_serv4 = list( Description = 'Pre-meal weight of graham cracker with plate for serving 4',
                                  Unit = "grams"),
    graham_post_w_plate_serv1 = list( Description = 'Post-meal weight of graham cracker with plate for serving 1',
                                   Unit = "grams"),
    graham_post_w_plate_serv2 = list( Description = 'Post-meal weight of graham cracker with plate for serving 2',
                                   Unit = "grams"),
    graham_post_w_plate_serv3 = list( Description = 'Post-meal weight of graham cracker with plate for serving 3',
                                   Unit = "grams"),
    graham_post_w_plate_serv4 = list( Description = 'Post-meal weight of graham cracker with plate for serving 4',
                                   Unit = "grams"),
    graham_serving2 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    graham_serving3 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    graham_serving4 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    graham_pre_w_o_plate = list( Description = 'Total pre-meal weight of graham cracker without plate for all servings',
                              Unit = "grams"),
    graham_pre_w_plate = list( Description = 'Total pre-meal weight of graham cracker with plate for all servings',
                            Unit = "grams"),
    graham_post_w_plate = list( Description = 'Total post-meal weight of graham cracker with plate ffor all servings',
                             Unit = "grams"),

    #water
    water_pre_w_o_plate_serv1 = list( Description = 'Pre-meal weight of water without plate for serving 1',
                                    Unit = "grams"),
    water_pre_w_plate_serv1 = list( Description = 'Pre-meal weight of water with plate for serving 1',
                                  Unit = "grams"),
    water_pre_w_o_plate_serv2 = list( Description = 'Pre-meal weight of water without plate for serving 2',
                                    Unit = "grams"),
    water_pre_w_plate_serv2 = list( Description = 'Pre-meal weight of water with plate for serving 2',
                                  Unit = "grams"),
    water_pre_w_o_plate_serv3 = list( Description = 'Pre-meal weight of water without plate for serving 3',
                                    Unit = "grams"),
    water_pre_w_plate_serv3 = list( Description = 'Pre-meal weight of water with plate for serving 3',
                                  Unit = "grams"),
    water_pre_w_o_plate_serv4 = list( Description = 'Pre-meal weight of water without plate for serving 4',
                                    Unit = "grams"),
    water_pre_w_plate_serv4 = list( Description = 'Pre-meal weight of water with plate for serving 4',
                                  Unit = "grams"),
    water_post_w_plate_serv1 = list( Description = 'Post-meal weight of water with plate for serving 1',
                                   Unit = "grams"),
    water_post_w_plate_serv2 = list( Description = 'Post-meal weight of water with plate for serving 2',
                                   Unit = "grams"),
    water_post_w_plate_serv3 = list( Description = 'Post-meal weight of water with plate for serving 3',
                                   Unit = "grams"),
    water_post_w_plate_serv4 = list( Description = 'Post-meal weight of water with plate for serving 4',
                                   Unit = "grams"),
    water_serving2 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    water_serving3 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    water_serving4 = list( Description = 'Serving 2 requested by child',
                         Levels = list( '1' = 'Yes',
                                        '0' = 'No')),
    water_pre_w_o_plate = list( Description = 'Total pre-meal weight of water without plate for all servings',
                              Unit = "grams"),
    water_pre_w_plate = list( Description = 'Total pre-meal weight of water with plate for all servings',
                            Unit = "grams"),
    water_post_w_plate = list( Description = 'Total post-meal weight of water with plate ffor all servings',
                             Unit = "grams")
  )

  # convert formatting to JSON
  intake_json <- RJSONIO::toJSON(intake_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(intake_json, asText = TRUE))){
    print('Intake JSON file may be invalid')
  }

  return(intake_json)

}
