#' json_social_dq: Generates a json file for the Social Desirability Questionnaire
#'
#' This function generates a json file for the scored Social Desirability Questionnaire and raw participant responses.
#'
#' @return A string with data stored in JSON format containing meta-data for the Social Desirability Questionnaire
#'
#'
#' @export

json_social_dq <- function() {

  social_dq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Social Desirability Questionnaire. Trained research assistants said: "Okay, now I have some questions for you about what you normally do or what you normally feel. There are no right or wrong answers, I just want to know what YOU normally do or feel. Does that make sense?" and then adminsitered the scale to children by reading each pairs of question',
      Reference = 'Ford LH. A social desirability questionnaire for young children. Journal of Consulting and Clinical Psychology 1970; 35(2):195-204.',
      TermURL = ''),
    participant_id = list( Description = 'participant id number'),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('2' =	'Child visit protocol 1',
                                          '3' =	'Child visit protocol 2',
                                          '3' =	'Child visit protocol 3',
                                          '4'	= 'Child visit protocol 4',
                                          '5'	= 'Child visit protocol 5')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),
    sdq1 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes play with toys?',
                                '2' = '2. Do you never play with toys?',
                                '3' = 'Prefer not to answer')),
    sdq2 = list( Description = '',
                 Levels = list ('1' = '1. Do you always play all by yourself?',
                                '2' = '2. Do you sometimes play all by yourself?',
                                '3' = 'Prefer not to answer')),
    sdq3 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes argue with your mother?',
                                '2' = '2. Do you never argue with your mother?',
                                '3' = 'Prefer not to answer')),
    sdq4 = list( Description = '',
                 Levels = list ('1' = '1. Are you always polite to older people?',
                                '2' = '2. Are you sometimes not polite to older people?',
                                '3' = 'Prefer not to answer')),
    sdq5 = list( Description = '',
                 Levels = list ('1' = '1. Do you never shout when you feel angry?',
                                '2' = '2. Do you sometimes shout when you feel angry?',
                                '3' = 'Prefer not to answer')),
    sdq6 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes tell a little lie?',
                                '2' = '2. Do you never tell a little lie?',
                                '3' = 'Prefer not to answer')),
    sdq7 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes hit another boy or girl? ',
                                '2' = '2. Do you never hit another boy or girl?',
                                '3' = 'Prefer not to answer')),
    sdq8 = list( Description = '',
                 Levels = list ('1' = '1. Do you always help people?',
                                '2' = '2. Do you sometimes not help people?',
                                '3' = 'Prefer not to answer')),
    sdq9 = list( Description = '',
                 Levels = list ('1' = '1. Do you never show off to your friends? ',
                                '2' = '2. Do you sometimes show off to your friends?',
                                '3' = 'Prefer not to answer')),
    sdq10 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes say mean things to people?',
                                '2' = '2. Do you never say mean things to people?',
                                '3' = 'Prefer not to answer')),
    sdq11 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes feel like throwing or breaking things?',
                                '2' = '2. Do you never feel like throwing or breaking things?',
                                '3' = 'Prefer not to answer')),
    sdq12 = list( Description = '',
                 Levels = list ('1' = '1. Do you feel that your parents are always right?',
                                '2' = '2. Do you feel like your parents are not always right?',
                                '3' = 'Prefer not to answer')),
    sdq13 = list( Description = '',
                 Levels = list ('1' = '1. Do you never act naughty?',
                                '2' = '2. Do you sometimes act naughty?',
                                '3' = 'Prefer not to answer')),
    sdq14 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes do other things instead of what your teacher tells you to do?',
                                '2' = '2. Do you always do what your teacher tells you to do?',
                                '3' = 'Prefer not to answer')),
    sdq15 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes do things you\'re not supposed to?',
                                '2' = '2. Do you never do things you\'re not supposed to?',
                                '3' = 'Prefer not to answer')),
    sdq16 = list( Description = '',
                 Levels = list ('1' = '1. Do you think your teachers know more than you do?',
                                '2' = '2. Do you think you know more than your teacher does? (I know more)',
                                '3' = 'Prefer not to answer')),
    sdq17 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes want things your parents don\'t want you to have? ',
                                '2' = '2. Do you never want things your parents don\'t want you to have?',
                                '3' = 'Prefer not to answer')),
    sdq18 = list( Description = '',
                 Levels = list ('1' = '1. Does it sometimes bother you when you don\'t get your way?',
                                '2' = '2. Does it never bother you when you don\'t get your way?',
                                '3' = 'Prefer not to answer')),
    sdq19 = list( Description = '',
                 Levels = list ('1' = '1. Do you always listen to your parents?',
                                '2' = '2. Do you sometimes not listen to your parents?',
                                '3' = 'Prefer not to answer')),
    sdq20 = list( Description = '',
                 Levels = list ('1' = '1. Do you always wash your hands before every meal?',
                                '2' = '2. Do you sometimes not wash your hands before every meal?',
                                '3' = 'Prefer not to answer')),
    sdq21 = list( Description = '',
                 Levels = list ('1' = '1. Do you never feel like making fun of other people?',
                                '2' = '2. Do you sometimes feel like making fun of other people?',
                                '3' = 'Prefer not to answer')),
    sdq22 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes forget to say "please" and "thank you"?',
                                '2' = '2. Do you never forget to say "please" and "thank you"?',
                                '3' = 'Prefer not to answer')),
    sdq23 = list( Description = '',
                 Levels = list ('1' = '1. Does it sometimes bother you to share things with your friends?',
                                '2' = '2. Does it never bother you to share things with your friends?',
                                '3' = 'Prefer not to answer')),
    sdq24 = list( Description = '',
                 Levels = list ('1' = '1. Do you sometimes want to do things your parents tell you not to do?',
                                '2' = '2. Do you never want to do things your parents tell you not to do?',
                                '3' = 'Prefer not to answer')),
    sdq25 = list( Description = '',
                  Levels = list ('1' = '1. Do you never get angry?',
                                 '2' = '2. Do you sometimes get angry?',
                                 '3' = 'Prefer not to answer')),
    sdq26 = list( Description = '',
                  Levels = list ('1' = '1. Are you always nice to people?',
                                 '2' = '2. Are you sometimes not nice to people?',
                                 '3' = 'Prefer not to answer')),
    sdq27 = list( Description = '',
                  Levels = list ('1' = '1. Do you sometimes not do the right things?',
                                 '2' = '2. Do you always do the right things?',
                                 '3' = 'Prefer not to answer')),
    sdq28 = list( Description = '',
                  Levels = list ('1' = '1. Do you always tell the truth?',
                                 '2' = '2. Do you sometimes not tell the truth?',
                                 '3' = 'Prefer not to answer')),
    sdq_total = list( Description = 'Total score',
                     Derivative = TRUE))

  # convert formatting to JSON
  social_dq_json <- RJSONIO::toJSON(social_dq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(social_dq_json, asText = TRUE))){
    print('Body Esteem JSON file may be invalid')
  }

  return(social_dq_json)

}
