#' json_household: Generates a json file for the household demographic questionnaire
#'
#' This function provides a json file for household demographic questionnaire collected in Apple Study
#'
#' @return A string with data stored in JSON format containing meta-data for the household demographic questionnaire
#'
#'
#' @export

json_household <- function() {

  household_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'A collection of items to assess parent demographics and household environment. This questionnaire was developed within the Keller Lab for Study REACH. Participants were provided the following instructions: "Please answer the following questions:"'),
    participant_id = list( Description = 'participant id number'),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    demo_birth_number = list( Description = 'What is the birth number of the child in the study (E.g. If the child is first born, enter 1)'),
    demo_child_relationship = list( Description = 'What is your relationship to the child in the study?',
                                    Levels = list ('0' = 'Mother',
                                                   '1' = 'Father',
                                                   '2' = 'Other')),
    demo_parent_ethnicity = list( Description = 'What is your ethnicity?',
                                  Levels = list ('0' = 'Hispanic or Latino',
                                                 '1' = 'Not Hispanic or Latino')),
    demo_parent_race = list( Description = 'What is your race?',
                             Levels = list ('0' = 'American Indian/Alaskan Native',
                                            '1' = 'Asian',
                                            '2' = 'Black or African American',
                                            '3' = 'White',
                                            '4' = 'Hawaiian/Pacific Islander',
                                            '5' = 'Other')),
    demo_parent_other_race = list( Description = 'Other race (please state):'),
    demo_live_mother = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Mother'),
    demo_live_father = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Father'),
    demo_live_siblings = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Siblings'),
    demo_live_uncle = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Uncle'),
    demo_live_aunt = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Aunt'),
    demo_live_grandma = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Grandmother'),
    demo_live_grandpa = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Grandfather'),
    demo_live_cousins = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Cousin'),
    demo_live_other = list( Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Other'),
    demo_household_people_other = list(Description = 'Please indicate the people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in): Describe why you indicated Other'),
    demo_parent_seperations = list( Description = 'How many parental/parental figure separations has your child experienced? (Enter a number)'),
    demo_foster_care = list( Description = 'How many foster care placements has your child experienced, prior to his/her current living arrangement? (Enter a Number)'),
    demo_partner = list( Description = 'Do you have a spouse, partner, or significant other?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    demo_marital_status = list( Description = 'What is your martial status?',
                                  Levels = list ('0' = 'Married',
                                                 '1' = 'Single (never married)',
                                                 '2' = 'Widowed',
                                                 '3' = 'Divorced',
                                                 '4' = 'Separated',
                                                 '5' = 'Remarried',
                                                 '6' = 'Living together (not married)')),
    demo_income = list( Description = 'Including ALL sources (such as social security income, child support payments, government assistance, dividends from investments, etc.) what was your household\'s combined yearly income last year BEFORE taxes?',
                        Levels = list ('0' = 'Less than $20,000',
                                       '1' = '$20,000 - $35,999',
                                       '2' = '$36,000 - $50,999',
                                       '3' = '$51,000 - $75,999',
                                       '4' = '$76,000 - $100,000',
                                       '5' = '$100,000 +')),
    demo_education_mom = list( Description = 'Mom level of education (if demo_child_relationship = 0)',
                               Derivative = TRUE,
                               Levels = list ('0' = 'High School or GED (12 years)',
                                              '1' = 'Associate degree (14 years)',
                                              '2' = 'Technical/Vocational school (14 years)',
                                              '3' = 'Bachelor\'s Degree (16 years)',
                                              '4' = 'Master\'s degree (18 years)',
                                              '5' = 'PhD (20+ years)',
                                              '6' = 'MD (20+ years)',
                                              '7' = 'JD (20+ years)',
                                              '8' = 'Other')),
    demo_education_parent = list( Description = 'What is your highest level of formal education?',
                                  Levels = list ('0' = 'High School or GED (12 years)',
                                                 '1' = 'Associate degree (14 years)',
                                                 '2' = 'Technical/Vocational school (14 years)',
                                                 '3' = 'Bachelor\'s Degree (16 years)',
                                                 '4' = 'Master\'s degree (18 years)',
                                                 '5' = 'PhD (20+ years)',
                                                 '6' = 'MD (20+ years)',
                                                 '7' = 'JD (20+ years)',
                                                 '8' = 'Other')),
    demo_parent_education_other = list( Description = 'If other, please describe'),
    demo_employed = list( Description = 'Are you currently employed?',
                          Levels = list ('0' = 'No',
                                         '1' = 'Yes')),
    demo_work_hours = list( Description = 'How many hours per week are you at work (not traveling to and from)?'),
    demo_retired = list( Description = 'Are you currently retired?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    demo_partner_employment = list( Description = 'Is your spouse, partner, or significant other currently employed?'),
    demo_partner_workhours = list( Description = 'How many hours per week is your spouse, partner, or significant other at work (not traveling to and from)?'),
    demo_partner_retired = list( Description = 'Is your spouse, partner, or significant other currently retired?',
                                 Levels = list ('0' = 'No',
                                                '1' = 'Yes')),
    demo_weight_past_month = list( Description = 'Has your child\'s biological mother lost or gained 10 or more pounds in the past month?',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_feeding_child = list( Description = 'Who is primarily responsible for feeding your child?',
                               Levels = list ('0' = 'You',
                                              '1' = 'Your partner',
                                              '2' = 'Both',
                                              '3' = 'School',
                                              '4' = 'Other')),
    demo_buys_food = list( Description = 'Who is primarily responsible for buying food in your household?',
                           Levels = list ('0' = 'You',
                                          '1' = 'Your partner',
                                          '2' = 'Both',
                                          '3' = 'Other')),
    demo_eat_out = list( Description = 'On average, how frequently does your family eat out or get delivery/take out for dinner?',
                         Levels = list ('0' = 'Once a month or less',
                                        '1' = 'Twice a month',
                                        '2' = 'Once a week',
                                        '3' = 'Two times a week',
                                        '4' = 'Three times a week',
                                        '5' = 'Four or more times a week')),
    demo_dinner_together = list( Description = 'On average, how many nights a week does your family eat dinner together as a group (with most family members present)?'),
    demo_prepared_lunch = list( Description = 'On average, how many times per week does your child eat lunch that he/she brings from home?'),
    demo_food_condition = list( Description = 'Does anyone in your household have a condition that affects the food they eat?',
                                Levels = list ('0' = 'No',
                                               '1' = 'Yes')),
    demo_food_condition_desc = list( Description = 'If yes, describe the condition that affects the food they eat?'),
    demo_assist_program_snap = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: SNAP (food stamps)',
                                     Levels = list ('0' = 'No',
                                                    '1' = 'Yes')),
    demo_assist_program_wic = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: WIC',
                                    Levels = list ('0' = 'No',
                                                   '1' = 'Yes')),
    demo_assist_program_tnaf = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: TNAF (cash assistance)',
                                     Levels = list ('0' = 'No',
                                                    '1' = 'Yes')),
    demo_assist_program_medicaid = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Medicaid (Medical assistance)',
                                         Levels = list ('0' = 'No',
                                                        '1' = 'Yes')),
    demo_assist_program_liheap = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: LIHEAP (Home energy assistance)',
                                       Levels = list ('0' = 'No',
                                                      '1' = 'Yes')),
    demo_assist_program_pfr_lunch = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Partial Free/Reduced School Meal Program (only some meals)',
                                          Levels = list ('0' = 'No',
                                                         '1' = 'Yes')),
    demo_assist_program_fr_lunch = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Full Free/Reduced School Meal Programs',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_assist_program_other = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Other assistance programs',
                                      Levels = list ('0' = 'No',
                                                     '1' = 'Yes')),
    demo_food_pantry = list( Description = 'Have you ever received food from a food pantry or soup kitchen?',
                             Levels = list ('0' = 'No',
                                            '1' = 'Yes')),
    demo_foodpantry_times = list( Description = 'How many times have you received food from a food pantry or soup kitchen in the past 12 months?'),
    demo_food_costs = list( Description = 'In a typical month, how much money do you spend on food for your household, including food you buy at any stores and restaurants?',
                            Levels = list ('0' = 'Less than $100 a month',
                                           '1' = '$100 - $200 a month',
                                           '2' = '$200 - $300 a month',
                                           '3' = '$300 - $400 a month',
                                           '4' = '$400 - $500 a month',
                                           '5' = 'More than $500 a month')),
    demo_store_choice = list( Description = 'Which grocery store do you use most often when going on a typical food shopping trip?',
                              Levels = list ('0' = 'Giant',
                                             '1' = 'Sam\'s Club',
                                             '2' = 'Target',
                                             '3' = 'Trader Joe\'s',
                                             '4' = 'Walmart',
                                             '5' = 'Wegmans',
                                             '6' = 'Weis',
                                             '7' = 'A speciality of international food store, such as International Market',
                                             '8' = 'Other')),
    demo_grow_fruit = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Fruits',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_veg = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Vegetables',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_spreads = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Jelly, jam, or any other spreads/dips made from your fruits or vegetables',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_nutseeds = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Nuts or seeds',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_milk = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Milk',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_cheese = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Cheese',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_butter = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Butter',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_eggs = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Eggs',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_redmeat = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Red meat',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_poultry = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Poultry meat',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_grow_none = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Do not produce any of these food items',
                                    Levels = list ('0' = 'No',
                                                   '1' = 'Yes')),
    demo_allowance = list( Description = 'Does your child get money as an allowance?',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
    demo_allowance_amt = list( Description = 'About how much money per week do you give your child for their allowance?',
                                 Levels = list ('0' = 'Less than $1 a week',
                                                '1' = '$1 - $5 a week',
                                                '2' = 'More than $5 a week')),
    demo_parent_age = list( Description = 'Age of parent calculated from self-reported parent date of birth (data not shared) and date of form completion (data not shared)',
                            Unit = "years",
                            Derivative = TRUE))

  # convert formatting to JSON
  household_json <- RJSONIO::toJSON(household_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(household_json, asText = TRUE))){
    print('household demo JSON file may be invalid')
  }

  return(household_json)

}
