#' json_pst: Generates a json file for the child portion size task
#'
#' This function generates a json file for he child portion size task
#'
#' @return A string with data stored in JSON format containing meta-data
#'
#'
#' @export

json_pst <- function() {

  pst_list <- list(
    participant_id = list( Description = 'participant id number'),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1',
                                          '2' =	'Child visit protocol 2',
                                          '3' =	'Child visit protocol 3',
                                          '4'	= 'Child visit protocol 4',
                                          '5'	= 'Child visit protocol 5')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    pst_pre_fullness = list( Description = 'Pre-PST task fullness rating on a 4 point likert scale with 4 images of a child with their belly full to varying extents',
                                Levels = list ('0' = 'Empty Belly',
                                               '1' = 'Partly Full',
                                               '2' = 'Almost Full',
                                               '3' = 'Full Belly')),
    pst_match1_time = list( Description = 'Time to complete the first portion size matching game with 16 itmes',
                                Unit = 'M:S'),
    pst_match2_time = list( Description = 'Time to complete the second portion size matching game with 16 itmes',
                               Unit = 'M:S'),
    pst_sort1 = list( Description = 'Portion Sorting for: ',
                               Levels = list ('0' = 'Too Little',
                                              '1' = 'Just Right',
                                              '2' = 'Too Much')),
    pst_sort2 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort3 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort4 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort5 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort6 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort7 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort8 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort9 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort10 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort11 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort12 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort13 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort14 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort15 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort16 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort17 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort18 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort19 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort20 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort21 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort22 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort23 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort24 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort25 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort26 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort27 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort28 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort29 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort30 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort31 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort32 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort33 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort34 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort35 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort36 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort37 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort38 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort39 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much')),
    pst_sort40 = list( Description = 'Portion Sorting for: ',
                      Levels = list ('0' = 'Too Little',
                                     '1' = 'Just Right',
                                     '2' = 'Too Much'))
  )

  # convert formatting to JSON
  pst_json <- RJSONIO::toJSON(pst_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(pst_json, asText = TRUE))){
    print('PST JSON file may be invalid')
  }

  return(pst_json)
}
