#' util_merged_intake: merges and formats all data related to meals and EAH
#'
#' This function merges all data related to meals and EAH and calculates intake values
#'
#'
#' @param child_v1_data full set of child visit 1 data generated by util_redcap_child_v1
#' @param child_v2_data full set of child visit 3 data generated by util_redcap_child_v3
#' @param child_v3_data full set of child visit 3 data generated by util_redcap_child_v3
#' @param child_v4_data full set of child visit 4 data generated by util_redcap_child_v4
#' @param child_v5_data full set of child visit 5 data generated by util_redcap_child_v5
#' @param proc_de_data full set of processed double-entry data generated by util_redcap_de
#' @examples
#'
#' # process data
#' merged_intake <- util_merged_intake(child_v1_data, child_v3_data, child_v4_data, child_v5_data, proc_de_data)
#'
#' @seealso [proc_redcap()], [util_redcap_child_v1()], [util_redcap_child_v3()], [util_redcap_child_v4()], [util_redcap_child_v5()], [util_redcap_de()], [util_calc_intake()]
#'
#' @export
#'


util_merged_intake <- function(child_v1_data, child_v2_data, child_v3_data, child_v4_data, child_v5_data, proc_de_data) {

  # liking
  liking_all <- rbind.data.frame(child_v1_data$liking_data$data, child_v2_data$liking_data$data, child_v3_data$liking_data$data, child_v4_data$liking_data$data)
  liking_all <- rbind(data.table::setDT(liking_all), data.table::setDT(child_v5_data$liking_data$data), fill = TRUE)
  liking_all <- as.data.frame(liking_all)

  #fullness
  fullness_all <- rbind.data.frame(child_v1_data$fullness_data$data, child_v2_data$fullness_data$data, child_v3_data$fullness_data$data, child_v4_data$fullness_data$data)
  fullness_all <- rbind(data.table::setDT(fullness_all), data.table::setDT(child_v5_data$fullness_data$data), fill = TRUE)
  fullness_all <- as.data.frame(fullness_all)

  #paradigm info
  food_paradigm_info_all <- rbind.data.frame(child_v1_data$food_paradigm_info$data, child_v2_data$food_paradigm_info$data, child_v3_data$food_paradigm_info$data, child_v4_data$food_paradigm_info$data)
  food_paradigm_info_all <- rbind(data.table::setDT(food_paradigm_info_all), data.table::setDT(child_v5_data$food_paradigm_info$data), fill = TRUE)
  food_paradigm_info_all <- as.data.frame(food_paradigm_info_all)


  # non-double entered (participants 1-16)
  intake_data_notde_all <- rbind(data.table::setDT(child_v1_data$intake_data$data), data.table::setDT(child_v2_data$intake_data$data), data.table::setDT(child_v3_data$intake_data$data), data.table::setDT(child_v4_data$intake_data$data), data.table::setDT(child_v5_data$intake_data$data), fill = TRUE)
  intake_data_notde_all <- as.data.frame(intake_data_notde_all)

  intake_all <- rbind(data.table::setDT(proc_de_data$intake_v1$data), data.table::setDT(proc_de_data$intake_v2$data), data.table::setDT(proc_de_data$intake_v3$data), data.table::setDT(proc_de_data$intake_v4$data), data.table::setDT(proc_de_data$intake_v5$data), fill = TRUE)
  intake_all <- as.data.frame(intake_all)
  names(intake_all)[names(intake_all) == 'preload'] <- 'preload_condition'


  # remove 1-16 with NA values
  intake_all <- intake_all[!is.na(intake_all['preload_condition']), ]

  # get those without double entry
  intake_data_notde_all <- intake_data_notde_all[!(intake_data_notde_all[['participant_id']] %in% intake_all[['participant_id']]), ]

  # merge de and non-de data
  intake_all <- rbind(data.table::setDT(intake_data_notde_all), data.table::setDT(intake_all), fill = TRUE)
  intake_all <- as.data.frame(intake_all)

  intake_all <- util_calc_intake(intake_all)

  intake_all <- intake_all[!grepl('intake', names(intake_all))]

  intake_all <- intake_all[c('participant_id', 'visit_protocol', 'visit_date', names(intake_all)[grepl('preload', names(intake_all))], names(intake_all)[grepl('mac', names(intake_all))], names(intake_all)[grepl('broccoli', names(intake_all))], names(intake_all)[grepl('grapes', names(intake_all))],names(intake_all)[grepl('carrots', names(intake_all))], names(intake_all)[grepl('graham', names(intake_all))], names(intake_all)[grepl('water', names(intake_all))], names(intake_all)[grepl('meal', names(intake_all))], names(intake_all)[grepl('chips', names(intake_all))], names(intake_all)[grepl('mms', names(intake_all))], names(intake_all)[grepl('brownies', names(intake_all))], names(intake_all)[grepl('cookies', names(intake_all))], names(intake_all)[grepl('starburst', names(intake_all))], names(intake_all)[grepl('fritos', names(intake_all))], names(intake_all)[grepl('eah', names(intake_all))], names(intake_all)[grepl('total', names(intake_all))])]

  #merge

  merged_intake <- merge(food_paradigm_info_all, liking_all[!grepl('visit_protocol|visit_date', names(liking_all))], by=c('participant_id', 'preload_condition'), all = TRUE)
  merged_intake <- merge(merged_intake, fullness_all[!grepl('visit_protocol|visit_date', names(fullness_all))], by=c('participant_id', 'preload_condition'), all = TRUE)

  merged_intake <- merge(merged_intake, intake_all[!grepl('visit_protocol|visit_date', names(intake_all))], by=c('participant_id', 'preload_condition'), all = TRUE)

  # return data
  return(merged_intake)

}
